### ISSUE TITLE
NullPointerException in FastISOTimestampFormatter in Argentina Time Zone

### ISSUE THREAD

**Issue by kmccarp** [logfellow/logstash-logback-encoder#796] opened 2022-04-12 22:56 UTC
**Describe the bug**
NullPointerException in https://github.com/logfellow/logstash-logback-encoder/blob/a8ab3aaee2f8dc026f750f5d7a220266272a7dce/src/main/java/net/logstash/logback/composite/FastISOTimestampFormatter.java#L186

It looks like this might be fixed with https://github.com/logfellow/logstash-logback-encoder/commit/0b42d878fed1628f0291f11c14801955e386f22d ?

**To Reproduce**
1. Try to run a spring boot application that has a dependency on logstash-logback-encoder in a time zone that has no transitions (e.g. America/Argentina/Rio_Gallegos)
2. That's the only step

**Expected behavior**
Expected spring server to start up

* what output did you expect

**Additional context**

* logstash-logback-encoder version: 7.1

Stack trace:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appenderConfigurer' defined in class path resource [foo.bar/common/monitoring/MonitoringAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [foo.bar.common.monitoring.MonitoringAppenderConfigurer]: Factory method 'appenderConfigurer' threw exception; nested exception is java.lang.NullPointerException
  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.15.jar:5.3.15]
  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.15.jar:5.3.15]
  at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[spring-boot-2.5.9.jar:2.5.9]
  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.5.9.jar:2.5.9]
  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:447) ~[spring-boot-2.5.9.jar:2.5.9]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.9.jar:2.5.9]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1356) ~[spring-boot-2.5.9.jar:2.5.9]
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1345) ~[spring-boot-2.5.9.jar:2.5.9]
  at foo.bar.scm.Application.main(Application.java:35) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [foo.bar.common.monitoring.MonitoringAppenderConfigurer]: Factory method 'appenderConfigurer' threw exception; nested exception is java.lang.NullPointerException
  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.15.jar:5.3.15]
  at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.15.jar:5.3.15]
  ... 19 common frames omitted
Caused by: java.lang.NullPointerException: null
  at net.logstash.logback.composite.FastISOTimestampFormatter$ZoneOffsetState.<init>(FastISOTimestampFormatter.java:186) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.composite.FastISOTimestampFormatter.<init>(FastISOTimestampFormatter.java:70) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.composite.FastISOTimestampFormatter.isoOffsetDateTime(FastISOTimestampFormatter.java:99) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.createTimestampWriter(AbstractFormattedTimestampJsonProvider.java:198) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.updateTimestampWriter(AbstractFormattedTimestampJsonProvider.java:177) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.<init>(AbstractFormattedTimestampJsonProvider.java:154) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider.<init>(LoggingEventFormattedTimestampJsonProvider.java:23) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.LogstashFormatter.<init>(LogstashFormatter.java:70) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.LogstashFormatter.<init>(LogstashFormatter.java:104) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.LogstashFormatter.<init>(LogstashFormatter.java:100) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.encoder.LogstashEncoder.createFormatter(LogstashEncoder.java:32) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.encoder.CompositeJsonEncoder.<init>(CompositeJsonEncoder.java:69) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder.<init>(LoggingEventCompositeJsonEncoder.java:26) ~[logstash-logback-encoder-7.1.jar:na]
  at net.logstash.logback.encoder.LogstashEncoder.<init>(LogstashEncoder.java:28) ~[logstash-logback-encoder-7.1.jar:na]
  at foo.bar.common.monitoring.MonitoringAppenderConfigurer.<init>(MonitoringAppenderConfigurer.java:67) ~[moderne-common-0.126.0.jar:na]
  at foo.bar.common.monitoring.MonitoringAutoConfiguration.appenderConfigurer(MonitoringAutoConfiguration.java:91) ~[moderne-common-0.126.0.jar:na]
  at foo.bar.common.monitoring.MonitoringAutoConfiguration$$EnhancerBySpringCGLIB$$b73e2e68.CGLIB$appenderConfigurer$7(<generated>) ~[moderne-common-0.126.0.jar:na]
  at foo.bar.common.monitoring.MonitoringAutoConfiguration$$EnhancerBySpringCGLIB$$b73e2e68$$FastClassBySpringCGLIB$$218254e9.invoke(<generated>) ~[moderne-common-0.126.0.jar:na]
  at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.15.jar:5.3.15]
  at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.15.jar:5.3.15]
  at foo.bar.common.monitoring.MonitoringAutoConfiguration$$EnhancerBySpringCGLIB$$b73e2e68.appenderConfigurer(<generated>) ~[moderne-common-0.126.0.jar:na]
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
  at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.15.jar:5.3.15]
  ... 20 common frames omitted
```

**Comment by brenuart** [comment] 2022-04-12 23:07
Duplicate of #794 (see issue description for workaround)

**Closed** 2022-04-12 23:07 UTC
