### ISSUE TITLE
Memory leak in RingBuffer() ?

### ISSUE THREAD

**Issue by lassancee** [logfellow/logstash-logback-encoder#738] opened 2022-01-05 11:44 UTC
**Describe the bug**
Following issue https://github.com/logfellow/logstash-logback-encoder/issues/110 fixed in version 4.4 (of which library btw?),
We have discovered another potential leak there:
![image](https://user-images.githubusercontent.com/97166906/148212514-1a5a7c90-02ae-4670-b822-b59666c7029c.png)

Note we have the version logstash-logback-encoder-4.9.jar

Is this supposed to be fixed ?
If yes, which version shall we download?

Many thanks for your advice,
_Eric_

**Comment by brenuart** [comment] 2022-01-05 12:12
The RingBuffer is initialised with `ringBufferSize` entries. Each entry is made of a `LogEvent` containing a reference to the `ILoggingEvent` created by Logstash. These references are cleared just after the event is handled by the async thread so the ILoggingEvent can be garbage collected. The size retained by a LogEvent depends on the size and references of the ILoggingEvent. This is usually small but can be larger especially if you added extra arguments (like deep object structures) when logging the event...

As you noticed versions of logstash-logback-encoder priori 4.4 did not clear the reference to the ILoggingEvent after processing. This is solved starting at version 4.4 and later. 

The version you are using (4.9) is already quite old and I have hard time to figure out what could be the problem... I suggest you give a try to the latest version (7.0.1) and see if you can reproduce the issue. Is that possible?

**Comment by lassancee** [comment] 2022-01-06 10:12
Thanks for the prompt feedback.
I am working in an Integration team so ok, I will ask my RnD team to rely on the latest logstash-logback-encoder Jar library version then we will replay the reproducer.

But just one thing please: I am a bit surprised to observ a very similar leak as the one described in https://github.com/logfellow/logstash-logback-encoder/issues/110  despite we are using a logstash-logback-encoder version > 4.4.
So could you please do a short code review to make sure the fix done in 4.4 has been well ported to the latest versions?...

**Comment by brenuart** [comment] 2022-01-06 11:02
I checked and I confirm the fix is present in version 4.9 you are using and in subsequent versions up to the latest.

What async appender are you using? The LogstashAccessTcpSocketAppender or the DelegatingAsyncDisruptorAppender?

Also as stupid it may seem please make sure the appender isn’t blocked and events aren’t simply waiting in the queue. If logging into a file, do you see new events being appended? If logging remotely, does the sink receive new events?

**Comment by lassancee** [comment] 2022-01-06 13:38
Baqed on the below extracted stack, I would say that our code relies on DelegatingAsyncDisruptorAppender:
![image](https://user-images.githubusercontent.com/97166906/148391226-f21463d7-4dd4-4ec0-9050-47a9b539a066.png)

**Comment by brenuart** [comment] 2022-01-06 14:06
The screenshot refers to AsyncDisruptorAppender which is a base class for all async implementation. You can tell which one you are using from the Logback.xml configuration file. Or easier: if you are logging on the console or in a file, then you are using the DelegatingAsyncDisruptorAppender. If you are sending logs remotely via TCP, you are probably using the TcpSocketAppender.

As I said earlier, you first have to make sure that events are correctly sent to the console, the file or whatever destination you have configured. If not they are likely to be stuck in the RingBuffer until the output is ready to accept them.

**Comment by brenuart** [comment] 2022-01-24 19:00
@lassancee Do you have any additional information/feedback since the last post?

**Comment by lassancee** [comment] 2022-01-25 07:36
Hello Bertrand,
After RnD team reviewed its source code, we concluded it was not necessary to upgrade logstash-logback-encoder, the problem was found in logback-spring.xml internal configuration for java microservices :
Our default configuration always tried to send the logs to configured logstash, but If logstash isn't present or not configured, that produces the memory leak at explained in your [comment](https://github.com/logfellow/logstash-logback-encoder/issues/738#issuecomment-1006617596)
So finally, we decided to add a new external configuration value to be set if our application should send logs to logstash or not (by default, nothing is sent to Logstash, it's up to end-user to enable that new property after he enables Logstash).

So thanks a lot for your help, your inputs really helped us and my RnD team.
You can close the ticket if you want.

**Comment by brenuart** [comment] 2022-01-25 09:48
Thanks for the feedback. Closing the issue. Do not hesitate to reopen or create a new one if needed.

**Closed by brenuart** 2022-01-25 09:48 UTC
Labels: status: waiting-for-feedback
